title: Sekwanele Njoko
theme: jekyll-theme-minimal
# Uncomment and edit the following lines if needed
# logo: "https://your-logo-link.com/logo.jpg"
# description: "Your description here"
# show_downloads: true
